id: P794323F7
initial_creation_type: input
source_metadata:
  title: Swift Rebirth Prayers
  language: it
  description: 'A selection of prayers for the swift rebirth (myur byon gsol ’debs)
    of prominent individuals (arranged alphabetically by subject):'
  volume:
    7875bbbdfd3342d1bcaf1403ec1818bb:
      title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the
        Supreme Tulku of the Fifth Drubwang Dzogchen Rinpoche'
      parent: Fifth Dzogchen Rinpoche
    7631f3153c844acc9c823ed812c481c0:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    5a232da143894d8ba47f0316702a9cbf:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      parent: Fourth Dodrupchen Rinpoche
    ad4fca333bcc4afd9fac97c9a4bd3975:
      title: Prayer for the Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    d702b1ece197436bb3e613c56b7e9385:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    cc52dab4a39647eb96c61303d17d365d:
      title: 'The Moonlight of Auspiciousness: A Yearning Prayer to the Noble and
        Glorious Guru Combined with an Aspiration for His Swift Return'
      parent: Gyurme Tsewang Gyatso
    fea93f52afb346db9592f19251064d3c:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Jamgön Kongtrul Lodrö Thaye
    8e23b2b745db4702a6d76aea51c94143:
      title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
      parent: Jamyang Khyenrab Tayé
    8bc10d899b95464c9d4fb2b9f4d8e568:
      title: Lamenting Prayer to Jamyang Chökyi Lodrö
      parent: Jamyang Khyentse Chökyi Lodrö
    649fa2683c85495c96980883e3e65ec2:
      title: 'Wondrous Light of the Moon: A Prayer for the Swift Appearance of the
        Supreme Tulku of Vajradhara'
      parent: Jamyang Loter Wangpo
    188b30e3495a449abbb115632ea4f4f0:
      title: 'The Swift Fulfilment of Wishes: Prayer for the Swift Appearance of the
        Supreme Tulku of the Mañjughoṣa Guru'
      parent: Katok Situ Chökyi Gyatso
    73a75fb7225d435bbf9ae856035e751d:
      title: 'Cymbals to Invoke a Compassionate Response: A Prayer for Swift Rebirth
        of Khandro Tsering Chödrön'
      parent: Khandro Tsering Chödrön
    dfc1a341bf9b4b7cbd99713d2177a4ea:
      title: 'The Swift Infusion of Blessings: A Lament and Prayer to Invoke the Wisdom
        Mind of Khenchen Vāgindra on the Occasion of His Passing into the Great Peace
        of the Dharmadhātu'
      parent: Ngawang Samten Lodrö
    d4b931ba74a74f8da07cd52d5101143b:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Tenpai Nyima Rinpoche
    e08718df246a41d29a5f2b5927eba48c:
      title: 'The Tambura of Devotion: A Prayer for the Swift Appearance of the Supreme
        Tulku of the All-Seeing Conqueror and Cardinal Guardian of the Land of Snows'
      parent: Thirteenth Dalai Lama
    6e58080094894a5b97f4f52351726880:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Trulshik Rinpoche
created_at: '2022-03-01T05:59:59.958780'
last_modified_at: '2022-03-01T05:59:59.958783'
